JeanColombel93/cultivate_app

- app/controllers/entries_controller.rb
- app/models/entry.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20210525161144_create_entries.rb
- db/migrate/20210525163402_add_content_to_entries.rb
- db/schema.rb
- test/controllers/entries_controller_test.rb
- test/models/entry_test.rb
Created the basic structure for the entries
Routes:
`resources :entries` -> All 7 routes
Entry model:
`rails g model user:references`
Controller:
all 7 methods (empty for now)
@annemano  Please review.
> Creating entries basic structure

- app/assets/stylesheets/actiontext.scss
- app/assets/stylesheets/application.scss
- app/controllers/entries_controller.rb
- app/javascript/packs/application.js
- app/models/entry.rb
- app/views/active_storage/blobs/_blob.html.erb
- app/views/entries/new.html.erb
- db/migrate/20210525174951_create_active_storage_tables.active_storage.rb
- db/migrate/20210525175433_remove_content_from_entries.rb
- db/migrate/20210525175926_create_action_text_tables.action_text.rb
- db/schema.rb
- package.json
- test/fixtures/action_text/rich_texts.yml
- yarn.lock
Installed active-storage
Installed action-text (table + front-end dependencies)
Edited the new and create entries methods so we can create new entries.
@annemano Please review, thank you !
> Installing action text

- app/controllers/entries_controller.rb
- app/views/entries/_form.html.erb
- app/views/entries/edit.html.erb
- app/views/entries/index.html.erb
- app/views/entries/new.html.erb
- app/views/entries/show.html.erb
- app/views/guided/entries/new.html.erb
- app/views/pages/home.html.erb
- db/migrate/20210526160922_add_title_to_entries.rb
- db/migrate/20210526175424_remove_title_from_entries.rb
- db/schema.rb
I just created the basic views and added "devise feature" in the entries controller so users can only see their entries.
I wanted to add a title column too but I finally removed it.
@annemano please review.
> Implement devise with entries controller methods

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_emoji.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_overlay.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar_temp.html.erb
- app/views/shared/_overlay.html.erb
@annemano basic styling structure added, please review. Thank you!
> added back styling structure, added home page elements, mood table

- app/controllers/guided/entries_controller.rb
- app/models/guided/entry_builder.rb
Just a quick fix: the model couldn't read session[:mood] so now I pass it as an argument from the controller.
> fixed an error with mood when creating guided entry

- app/assets/stylesheets/components/_doodle.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/javascript/components/doodle.js
- app/javascript/packs/application.js
- app/views/pages/doodle.html.erb
- app/views/pages/menu.html.erb
- config/routes.rb
@daniel-silverman : added doodling option! I also updated the path in the menu. But not clear to me yet how people can leave the doodle to go back to the home or menu page.
> Add doodling option

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_menu.scss
- app/views/pages/menu.html.erb
I'm not sure how the button on the home page got so large, but it is now fixed across the application.
On the "menu" page, the buttons will need to be properly directed as we implement features, but the page is now ready. Would you please review when you have a moment, @annemano ?
> fixed button size, placed buttons on menu page.

- app/assets/stylesheets/components/_card_entry.scss
- app/assets/stylesheets/components/_index.scss
- app/views/entries/index.html.erb
Basic style in place for index page. Show page still needs styling. @annemano would you mind reviewing and merging when possible?
> Style entries index page

- app/javascript/components/doodle.js
- app/views/pages/doodle.html.erb
You can now save the doodle on your computer or phone :)
> Add save option to doodle

- app/assets/stylesheets/components/_card_entry.scss
- app/assets/stylesheets/components/_card_entry_show.scss
- app/assets/stylesheets/components/_index.scss
- app/views/entries/show.html.erb
@annemano I started working on this then realized the date will need to change here, so I'm stopping touching this for the moment. 
I can fix the date here after you address the date on the index page.
> Style entries show

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- db/migrate/20210528181224_add_first_name_to_users.rb
- db/schema.rb
as discussed with Luis and Daniel
@daniel-silverman Just simple first_name added (So I can add to seeds file too) and using it on the homepage
> added first_name to user, not mandatory, and added it to homepage

- app/assets/stylesheets/components/_actiontext.scss
- app/assets/stylesheets/components/_card_entry_show.scss
- app/assets/stylesheets/components/_form.scss
- app/views/entries/_form.html.erb
- app/views/entries/new.html.erb
> minor touches to border and size of text field for new entry

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card_guided_entry.scss
- app/assets/stylesheets/pages/_guided_entry_new.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/entries/edit.html.erb
- app/views/guided/entries/new.html.erb
guided questions styled a bit before presentation. @annemano could you please merge?
> added a few style changes to the guided questions

- app/controllers/communities_controller.rb
- app/models/community.rb
- app/models/user.rb
- app/views/pages/menu.html.erb
Just made a few adjustments and changed the redirect for the Community button.
> Adjustements to community feature

- app/controllers/entries_controller.rb
> fixed order of entries in index

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_menu.scss
- app/views/pages/home.html.erb
- app/views/pages/menu.html.erb
- app/views/shared/_navbar.html.erb
Navbar now stretches across all browser sizes. The elements do not grow in size, but it sticks to the edges of the window now. @annemano please review when possible. Thank you.
> make navbar work across all browser sizes

- app/assets/stylesheets/components/_card_entry.scss
- app/assets/stylesheets/components/_card_entry_show.scss
- app/views/entries/_form.html.erb
- app/views/entries/edit.html.erb
- app/views/entries/new.html.erb
- app/views/entries/show.html.erb
New:
Edit:
Show:
@daniel-silverman : "Home" redirects to the mood page, so something to revisit if it makes sense to have a link that goes there from the Show page.
> Style show edit entry

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_community_card.scss
- app/assets/stylesheets/components/_community_form.scss
- app/views/communities/_community_request_fields.html.erb
- app/views/communities/index.html.erb
Changed the styling after our stand up discussion.![image](https://user-images.githubusercontent.com/43459137/120374109-1f1a8e00-c2e7-11eb-9def-6ba2027d12e4.png)![image](https://user-images.githubusercontent.com/43459137/120373938-ec709580-c2e6-11eb-99d4-b5870d802d07.png)
> Changes to css styling after stand up discussion

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_doodle.scss
- app/views/pages/doodle.html.erb
> Fix doodle btns

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_community_card.scss
- app/assets/stylesheets/components/_community_form.scss
- app/assets/stylesheets/components/_message.scss
- app/views/communities/_form.html.erb
- app/views/communities/edit.html.erb
- app/views/communities/new.html.erb
- app/views/communities/show.html.erb
> Style chat feature

- app/assets/stylesheets/components/_message.scss
- app/controllers/messages_controller.rb
- app/views/messages/_message.html.erb
- config/routes.rb
> Add delete message on chat

- app/views/entries/index.html.erb
- app/views/entries/show.html.erb
@daniel-silverman As discussed just now!
> Remove margin from edit

- app/views/entries/index.html.erb
- app/views/entries/show.html.erb
- app/views/pages/home.html.erb
- app/views/pages/menu.html.erb
> add ecstatic emoji

- app/views/entries/index.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
> Final seeds file

- app/assets/stylesheets/components/_actiontext.scss
- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_message.scss
- app/controllers/entries_controller.rb
- app/javascript/channels/community_channel.js
- app/views/communities/show.html.erb
- app/views/layouts/application.html.erb
- app/views/messages/_message.html.erb
- app/views/spotifies/_spotify.html.erb
- app/views/youtubes/_youtube.html.erb
…o the user count.
Shared entries are now "broadcast" in the communities chat so other users don't have to refresh the page to see them.
> Correct synchronicity in chat

- app/assets/stylesheets/components/_navbar.scss
> removed margin from navbar-brand
